### ISSUE TITLE
Inconsistent Ground Design

### ISSUE THREAD

**Issue by Jerjerzanne** [Jerjerzanne/Comp476Project#3]
**Is your feature request related to a problem? Please describe.**
The rooms have some inconsistent ground designs. Some of the borders do not match, and so do the grates. I could use a room @TheMelanieJoy  designed and redo all the grids, I just need one standard to base everything else on.

**Describe the solution you'd like**
A standard ground design could implemented be in the `Assets/Prefabs/Rooms/CubeRoom` prefab. Afterwards, cleaning up the tile palette to avoid using the wrong tiles again. Afterwards I can simply go over the other prefabs and copy the style that was redesigned.

**Describe alternatives you've considered**
We could use a fixed texture for the rooms, but that means we wont be use a tile palette. The rooms are 10x10 units if you want to try that. If you want to create a new tile palette you can also do that. It will not be too hard to restyle the prefabs.

<a href="https://imgbb.com/"><img src="https://i.ibb.co/2srzZsW/ground.png" alt="ground" border="0"></a>

**Comment by TheMelanieJoy** [comment]
For the floor tiles, a tile palette can still be used. I just need to touch up on the tiles to make sure they can be used regardless of its rotation. However, I think it would be simpler if we use a fixed texture for the walls. I will try to have the new tileset and wall textures pushed tomorrow

**Comment by Jerjerzanne** [comment]
Ok sweet, but I just want to say this is not urgent work at all. We can talk about it tomorrow.

**Comment by Jerjerzanne** [comment]
Everything looks great. Closing for now.
